config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    authenticated :user do
      root 'trips#index'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end
  devise_for :users

  resources :trips do
    scope module: :trips do
      resources :activities, except: %i[index show]
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :trip

  validates :description, presence: true
  validate :end_at_after_start_at, if: lambda {
    start_at.present? && end_at.present?
  }

  private

  def end_at_after_start_at
    return if start_at < end_at

    errors.add(:end_at, 'must be after the start at')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validate :end_at_after_start_at, if: lambda {
    start_at.present? && end_at.present?
  }

  private

  def end_at_after_start_at
    return if start_at < end_at

    errors.add(:end_at, 'must be after the start at')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips/activities_controller.rb
class Trips::ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip
  before_action :set_activity, only: %i[edit update destroy]

  def new
    @activity = Activity.new
  end

  def create
    @activity = @trip.activities.build(activity_params)

    if @activity.save
      flash[:success] = 'Activity was successfully created'
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @activity.update(activity_params)
      flash[:success] = 'Activity was successfully updated'
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def destroy
    @activity.destroy

    flash[:success] = 'Activity was successfully deleted'
    redirect_to trip_path(@trip)
  end

  private

  def set_trip
    @trip = current_user.trips.find(params[:trip_id])
  end

  def set_activity
    @activity = @trip.activities.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:description, :start_at, :end_at, :notes,
                                     :price, :category, :location)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trip, only: %i[show edit update destroy]

  def index
    @trips = current_user.trips.order(:created_at)
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.build(trip_params)

    if @trip.save
      flash[:success] = 'Trip was successfully created'
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def show
    @pie_chart_data = Trip::GraphData.fetch(@trip)
    @activities = @trip.activities.order(:start_at)
  end

  def edit; end

  def update
    if @trip.update(trip_params)
      flash[:success] = 'Trip was successfully updated'
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def destroy
    @trip.destroy

    flash[:success] = 'Trip was successfully deleted'
    redirect_to trips_path
  end

  private

  def set_trip
    @trip = current_user.trips.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:title, :start_at, :end_at, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def toastr_key(key)
    case key
    when 'notice', 'success'
      'success'
    when 'error', 'alert'
      'error'
    else
      'warning'
    end
  end

  def between(start_at, end_at)
    s = if start_at.present?
      l(start_at, format: :long)
    end
    s ||= '---'

    e = if end_at.present?
      l(end_at, format: :long)
    end
    e ||= '---'

    "#{s} - #{e}"
  end
end

app/views/layouts/_footer.html.slim
.text-center
  | Bruno Crivelaro -
  '
  = link_to 'https://github.com/bcrivelaro', target: '_blank' do
    span.fa.fa-github.fa-clickable
  '
  = link_to 'https://www.linkedin.com/in/brunosantoscrivelaro/', target: '_blank' do
    span.fa.fa-linkedin.fa-clickable

app/views/layouts/_messages.html.slim
- flash.each do |key, value|
  == "<script>toastr.#{toastr_key(key)}('#{value}');</script>"

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
  = link_to 'Simple Trip Planner', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarDefault" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarDefault" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarDefault.collapse.navbar-collapse
    - if user_signed_in?
      ul.navbar-nav.mr-auto
        li.nav-item
          = link_to 'Trips', root_path, class: 'nav-link'
        li.nav-item
        = link_to 'New trip', new_trip_path, class: 'nav-link'
      = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Simple Trip Planner
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'stylesheets', 'data-turbolinks-track': 'reload'
  body
    = render partial: 'layouts/navbar'
    .container
      = render partial: 'layouts/messages'
      = yield
    footer.footer.fixed-bottom
      .container
        = render partial: 'layouts/footer'

app/views/shared/_errors.html.slim
- if obj.errors.any?
  .card.border-danger.mb-3
    .card-body.text-danger
      h5.card-title= pluralize(obj.errors.count, "error")
      ul
        - obj.errors.full_messages.each do |msg|
          li
            = msg

app/views/trips/_activity_info.html.slim
.activity-info
  .row
    .col-md-9
      h5.activity-description
        = activity.description
        span.badge.badge-primary.category-icon= activity.category
      - if activity.location.present?
        span.fa.fa-map-marker
        .activity-location
          = activity.location
      .text-muted
        = between(activity.start_at, activity.end_at)
        = " (#{number_to_currency(activity.price, unit: '$')})"
      = activity.notes
    .col-md-3.valign
      .btn-group.btn-group-sm
        = link_to 'Edit', edit_trip_activity_path(@trip, activity), class: 'btn btn-secondary'
        = link_to 'Delete', trip_activity_path(@trip, activity),
                  method: :delete, data: { confirm: 'Are you sure?' },
                  class: 'btn btn-danger'

app/views/trips/_form.html.slim
= render 'shared/errors', obj: @trip

= form_for(@trip, html: { class: 'form-horizontal', role: 'form' }) do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    .row
      .col-md-6
        = f.label :start_at
        #trip-start-at.datetimepicker.input-group.date data-target-input="nearest"
          = f.text_field :start_at,
                        class: 'form-control datetimepicker-input',
                        data: { target: '#trip-start-at' }
          .input-group-append data-target="#trip-start-at" data-toggle="datetimepicker"
            .input-group-text
              i.fa.fa-calendar
      .col-md-6
        = f.label :end_at
        #trip-end-at.datetimepicker.input-group.date data-target-input="nearest"
          = f.text_field :end_at,
                        class: 'form-control datetimepicker-input',
                        data: { target: '#trip-end-at' }
          .input-group-append data-target="#trip-end-at" data-toggle="datetimepicker"
            .input-group-text
              i.fa.fa-calendar
  .form-group
    = f.label :notes
    = f.text_area :notes, class: 'form-control', rows: 10
  .form-group
    = f.submit class: 'btn btn-primary'

app/views/trips/_graphs.html.slim
= pie_chart @pie_chart_data, width: '300px', height: '200px', legend: 'right'

app/views/trips/activities/_form.html.slim
= render 'shared/errors', obj: @activity

= form_for([@trip, @activity], html: { class: 'form-horizontal', role: 'form' }) do |f|
  .form-group
    = f.label :description
    = f.text_field :description, class: 'form-control'
  .form-group
    .row
      .col-md-6
        = f.label :start_at
        #activity-start-at.datetimepicker.input-group.date data-target-input="nearest"
          = f.text_field :start_at,
                        class: 'form-control datetimepicker-input',
                        data: { target: '#activity-start-at' }
          .input-group-append data-target="#activity-start-at" data-toggle="datetimepicker"
            .input-group-text
              i.fa.fa-calendar
      .col-md-6
        = f.label :end_at
        #activity-end-at.datetimepicker.input-group.date data-target-input="nearest"
          = f.text_field :end_at,
                        class: 'form-control datetimepicker-input',
                        data: { target: '#activity-end-at' }
          .input-group-append data-target="#activity-end-at" data-toggle="datetimepicker"
            .input-group-text
              i.fa.fa-calendar
  .form-group
    .row
      .col-md-4
        = f.label :location
        = f.text_field :location, class: 'form-control'
      .col-md-4
        = f.label :category
        = f.text_field :category, class: 'form-control'
      .col-md-4
        = f.label :price
        = f.number_field :price, class: 'form-control', min: 0, step: 0.01
  .form-group
    = f.label :notes
    = f.text_area :notes, class: 'form-control', rows: 10
  .form-group
    = f.submit class: 'btn btn-primary'

app/views/trips/activities/edit.html.slim
h1 Edit activity for #{@trip.title}

= render 'form'

app/views/trips/activities/new.html.slim
h1 New activity for #{@trip.title}

= render 'form'

app/views/trips/edit.html.slim
h1 Edit trip

= render 'form'

app/views/trips/index.html.slim
- if @trips.any?
  table.table
    thead.thead-dark
      tr
        th Trip
        th Actions
    tbody
      - @trips.each do |trip|
        tr
          td= trip.title
          td
            .btn-group role="group"
              = link_to 'View', trip_path(trip), class: 'btn btn-primary'
              = link_to 'Edit', edit_trip_path(trip), class: 'btn btn-secondary'
              = link_to 'Delete', trip_path(trip),
                        method: :delete, data: { confirm: 'Are you sure?' },
                        class: 'btn btn-danger'
- else
  = link_to 'New trip', new_trip_path, class: 'btn btn-primary'

app/views/trips/new.html.slim
h1 New trip

= render 'form'

app/views/trips/show.html.slim
.row
  .col-md-6
    .card.border-primary
      .card-body
        h1.card-title= @trip.title
        .card-text
          p= between(@trip.start_at, @trip.end_at)
          p= @trip.notes

        = link_to 'Edit trip', edit_trip_path(@trip), class: 'btn btn-secondary', style: 'margin-right: 10px'
        = link_to 'Add activity', new_trip_activity_path(@trip), class: 'btn btn-primary'
  .col-md-6
    = render 'graphs', data: @trip_data

- if @activities.any?
  - @activities.each do |activity|
    br
    = render 'activity_info', activity: activity